[project]
name = "dr-nb-admin-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datarobot-pulumi-utils>=0.1.1",
    "pulumi>=3.204.0",
    "pulumi-datarobot>=0.10.21",
]
